mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import home

urlpatterns = [
    # path('', home),
    path("", include("tracker.urls")),
    path("admin/", admin.site.urls),
]

mysite/tracker/urls.py
from django.urls import path
from tracker import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'tracker'

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path("current_location", views.CurrentLocationView.as_view(), name="current_location"),
    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout"),
    path("update_tracker_data", views.UpdateTrackerData.as_view(), name="update_tracker_data"),
    path("delete_nth_trip", views.delete_nth_trip, name="delete_nth_trip"),
    path("calendar", views.CalendarView.as_view(), name="calendar"),
    path('trip_list', views.TripListView.as_view(), name='trip_list'),
]

urlpatterns += staticfiles_urlpatterns()

mysite/tracker/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class NameForm(forms.Form):
    your_name = forms.CharField(label="Your name", max_length=100)


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

mysite/tracker/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from django.views.generic import TemplateView, ListView
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.views import View
from django.urls import reverse
from django.core.paginator import Paginator

from .models import TrackerData, TripMetadata
from .forms import NewUserForm
from .utils import update_tracker_data, get_address, get_graph, get_trip_coordinates
from datetime import datetime, date, timedelta


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("tracker:index")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(
        request=request,
        template_name="tracker/register.html",
        context={"register_form": form},
    )


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("tracker:index")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(
        request=request,
        template_name="tracker/login.html",
        context={"login_form": form},
    )


def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("tracker:index")


# Homepage View (Trips)
class IndexView(TemplateView):
    template_name = "tracker/tracker.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Retrieve all trip indexes in a list
        trip_indexes_list = list(
            TripMetadata.objects.values_list("trip_index", flat=True)
        )
        last_trip_number = trip_indexes_list[-1]
        context["last_trip_number"] = last_trip_number

        # Retrieve the requested trip number from the URL parameter, defaulting to the last trip number
        trip_number = int(self.request.GET.get("trip_number", last_trip_number))

        # Check if the requested trip number is valid
        if trip_number not in trip_indexes_list:
            # Return a 404 error if the requested trip number does not exist
            raise Http404("Trip not found")

        context["trip_number"] = trip_number
        context["coordinates"] = get_trip_coordinates(trip_number)
        (
            context["start_address"],
            context["end_address"],
        ) = self.get_start_and_end_addresses(context["coordinates"])
        context["times"] = TripMetadata.get_times_for_trip(trip_number)
        context["top_speed"] = TrackerData.get_nth_trip_top_speed(trip_number)
        context["distance"] = TrackerData.get_nth_trip_distance(trip_number)

        # Add the graphs HTML to the context
        context["speed_graph_html"] = get_graph(
            trip_number, "can_vehicle_speed", "Vehicle Speed Graph", "Vehicle Speed"
        )
        context["temp_graph_html"] = get_graph(
            trip_number,
            "ble_temperature_1",
            "Interior Temperature Graph",
            "Interior Temperature",
        )
        context["coolant_temp_graph_html"] = get_graph(
            trip_number, "can_engine_coolant_temp", "Coolant Temp Graph", "Coolant Temp"
        )
        context["engine_rpm_graph_html"] = get_graph(
            trip_number, "can_engine_rpm", "Engine RPM Graph", "Engine RPM"
        )

        # Get the previous and next trip numbers for pagination
        prev_trip_number, next_trip_number = self.get_previous_and_next_trip_numbers(
            trip_indexes_list, trip_number
        )
        context["prev_trip_url"] = self.get_trip_url(prev_trip_number)
        context["next_trip_url"] = self.get_trip_url(next_trip_number)

        return context

    def get_start_and_end_addresses(self, coordinates):
        if coordinates:
            start_address = get_address(coordinates[0])
            end_address = get_address(coordinates[-1])
            return start_address, end_address
        return None, None

    def get_previous_and_next_trip_numbers(self, trip_indexes_list, trip_number):
        current_index = trip_indexes_list.index(trip_number)
        prev_trip_number = (
            trip_indexes_list[current_index - 1] if current_index > 0 else None
        )
        next_trip_number = (
            trip_indexes_list[current_index + 1]
            if current_index < len(trip_indexes_list) - 1
            else None
        )
        return prev_trip_number, next_trip_number

    def get_trip_url(self, trip_number):
        # Generate the trip URL if the trip number exists
        if trip_number is not None:
            return f"?trip_number={trip_number}"
        return None


class TripListView(ListView):
    model = TripMetadata
    template_name = "tracker/trip_list.html"
    paginate_by = 20
    context_object_name = "trip_list"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        trip_indexes_list = list(
            TripMetadata.objects.values_list("trip_index", flat=True)
        )
        last_trip_number = trip_indexes_list[-1]
        trip_number = int(self.request.GET.get("trip_number", last_trip_number))

        if trip_number not in trip_indexes_list:
            raise Http404("Trip not found")

        trip_data_list = []
        for trip_index in reversed(trip_indexes_list):
            start_datetime, end_datetime, _ = TripMetadata.get_times_for_trip(
                trip_index
            )
            distance = TrackerData.get_nth_trip_distance(trip_index)
            trip_data = {
                "Trip_ID": trip_index,
                "Start_datetime": start_datetime,
                "End_datetime": end_datetime,
                "Distance": distance,
            }
            trip_data_list.append(trip_data)

        paginator = Paginator(trip_data_list, self.paginate_by)
        page_number = self.request.GET.get("page")
        trip_list = paginator.get_page(page_number)

        context["trip_list"] = trip_list

        return context


class CalendarView(View):
    template_name = "tracker/calendar.html"

    def get(self, request):
        date_range = request.GET.get("date_range")

        if date_range:
            # Parse the date range string
            start_date_str, end_date_str = date_range.split(" - ")
            start_date = datetime.strptime(start_date_str, "%m/%d/%Y")
            end_date = datetime.strptime(end_date_str, "%m/%d/%Y") + timedelta(days=1)
        else:
            # Handle the case when no date range is selected
            today = date.today()
            start_date = datetime.combine(today, datetime.min.time()) - timedelta(
                days=6
            )
            end_date = start_date + timedelta(days=7)

        # Convert the start and end dates to timestamps
        start_timestamp = int(start_date.timestamp())
        end_timestamp = int(end_date.timestamp())

        coordinates = TrackerData.get_coordinates_for_date_range(
            start_timestamp, end_timestamp
        )

        if coordinates is None:
            coordinates = []
        # Create the context dictionary and add the desired data
        context = {
            "coordinates": coordinates,
            "start_date": start_date,
            "end_date": end_date,
        }

        return render(
            request=request, template_name="tracker/calendar.html", context=context
        )


def delete_nth_trip(request):
    if request.method == "POST":
        trip_number = int(request.POST.get("trip_number"))
        data = TrackerData.objects.order_by("-timestamp").first()
        success, message = data.delete_nth_trip_data(trip_number)
        if success:
            messages.info(request, message)
        else:
            messages.error(request, message)

    # Retrieve the list of trip indexes
    trip_indexes = TripMetadata.objects.values_list("trip_index", flat=True).order_by(
        "trip_index"
    )

    # Get the index of the next trip
    next_trip_index = trip_indexes.filter(trip_index__gt=trip_number).first()
    if next_trip_index is not None:
        trip_url = reverse("tracker:index") + f"?trip_number={next_trip_index}"
    else:
        # Redirect to the index page if there is no next trip
        trip_url = reverse("tracker:index")

    return redirect(trip_url)


class UpdateTrackerData(View):
    def get(self, request):
        result = update_tracker_data()
        messages.info(request, result)
        return redirect("tracker:index")


class CurrentLocationView(TemplateView):
    template_name = "tracker/current_location.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        data = TrackerData.objects.order_by("-timestamp").first()
        context["location"] = data.latitude, data.longitude

        context["address"] = get_address([data.latitude, data.longitude])
        return context

mysite/tracker/templates/tracker/calendar.html
{% extends 'base.html' %} {% block content%}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>


<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>

<script>
  $(document).ready(function() {
    var start = moment().subtract(6, 'days');
    var end = moment();
  
    function cb(start, end) {
      $("#kt_daterangepicker_4").val(start.format("MM/DD/YYYY") + " - " + end.format("MM/DD/YYYY"));
    }
  
    // Get the date range from the URL parameter
    var urlParams = new URLSearchParams(window.location.search);
    var dateRangeParam = urlParams.get("date_range");
    if (dateRangeParam) {
      var [startDateStr, endDateStr] = dateRangeParam.split(" - ");
      var startDate = moment(startDateStr, "MM/DD/YYYY");
      var endDate = moment(endDateStr, "MM/DD/YYYY");
      start = startDate.isValid() ? startDate : start;
      end = endDate.isValid() ? endDate : end;
    }
  
    $("#kt_daterangepicker_4").daterangepicker({
      startDate: start,
      endDate: end,
      ranges: {
        "Today": [moment(), moment()],
        "Yesterday": [moment().subtract(1, "days"), moment().subtract(1, "days")],
        "Last 7 Days": [moment().subtract(6, "days"), moment()],
        "Last 30 Days": [moment().subtract(29, "days"), moment()],
        "This Month": [moment().startOf("month"), moment().endOf("month")],
        "Last Month": [moment().subtract(1, "month").startOf("month"), moment().subtract(1, "month").endOf("month")]
      }
    }, cb);
  
    cb(start, end);
  });
  
</script>

<h3>Trip data by date</h3>

<div class="row g-3">
  <div class="col-md-8">
    <form action="{% url 'tracker:calendar' %}" method="get">
      <label class="form-label">Select the Date Range</label>
      <div class="input-group">
        <input class="form-control form-control-solid" id="kt_daterangepicker_4" name="date_range" />
      </div>
  </div>
  <div class="col-md-4 align-self-end">
    <div class="input-group">
      <button type="submit" class="btn btn-primary w-100">SHOW TRIPS DATA</button>
    </div>
    </form>
  </div>
</div>
<br/>


<div class="row">
  <div class="col-md-12">
    <div id="map" style="width: 100%; height: 600px"></div>
  </br>

    <script>
      {% include 'tracker/includes/map_markers.html' %}

      var map = L.map('map');
      var latlngs = {{coordinates}};
      var polyline = L.polyline(latlngs, {color: 'blue', weight: 5}).addTo(map);
      {% comment %} var marker_start = L.marker({{coordinates|last}}, {icon: greenIcon}).addTo(map);
      var marker_finish = L.marker({{coordinates|first}}, {icon: redIcon}).addTo(map); {% endcomment %}

      // zoom the map to the polyline
      map.fitBounds(polyline.getBounds());

      L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map);
    </script>
  </div>
  {% comment %} <div class="col-md-4">
    <h5>Trip details</h5>
    <p><strong>Start address:</strong></br>{{start_address}}</p>
    <p><strong>End address:</strong></br>{{end_address}}</p>
    <p><strong>Start time:</strong></br>{{times.0}}</p>
    <p><strong>End time:</strong></br>{{times.1}}</p>
    <p><strong>Duration:</strong></br>{{times.2}}</p>
    <p><strong>Distance:</strong></br>{{distance}} km</p>
    <p><strong>Top speed:</strong></br>{{top_speed}} km/h</p>
    <br> {% endcomment %}

    {% comment %} Add the delete button and form {% endcomment %}
    {% comment %} {% if user.is_authenticated %}
      <form method="post" action="{% url 'tracker:delete_nth_trip' %}">
        {% csrf_token %}
        <input type="hidden" name="trip_number" value="{{ trip_number }}">
        <button type="submit" class="btn btn-danger">Delete Trip</button>
      </form>
    {% else %}
      <p style="color:red">Log in to delete a trip</p>
    {% endif %}
  </div> {% endcomment %}
</div>

<!-- Add the Plotly CSS and JavaScript code -->
{% comment %} <style>
  /* Plotly CSS styles */
  #graph_placeholder {
    width: 100%;
    height: 500px; /* Adjust the height as needed */
  }
</style>

<script src="https://cdnjs.cloudflare.com/ajax/libs/plotly.js/2.24.2/plotly.min.js" integrity="sha512-dAXqGCq94D0kgLSPnfvd/pZpCMoJQpGj2S2XQmFQ9Ay1+96kbjss02ISEh+TBNXMggGg/1qoMcOHcxg+Op/Jmw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<div id="graph_placeholder">
  {{ speed_graph_html | safe }}
</div>

<div id="graph_placeholder">
  {{ temp_graph_html | safe }}
</div>

<div id="graph_placeholder">
  {{ coolant_temp_graph_html | safe }}
</div>

<div id="graph_placeholder">
  {{ engine_rpm_graph_html | safe }}
</div> {% endcomment %}

{% endblock %}

mysite/tracker/templates/tracker/current_location.html
{% extends 'base.html' %} {% block content%}

<h3>Latest car's location:</h3>
<p>{{location}}: {{address}}</p>

{% comment %} leaflet map {% endcomment %}
<p>Location on the map:</p>
<div id="map" style="width: 100%; height: 600px"></div>

<script>
  var map = L.map('map').setView([{{location.0}}, {{location.1}}], 13);
  var marker = L.marker([{{location.0}}, {{location.1}}]).addTo(map);
  marker.bindPopup("<b>Location address:</b><br>{{address}}").openPopup();
  L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map);
</script>

{% endblock %}

mysite/tracker/templates/tracker/login.html
{% extends "base.html" %} {% block content %} {% load crispy_forms_tags %}

<section class="vh-100">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-xl-10">
        <div class="card" style="border-radius: 1rem">
          <div class="row g-0">
            <div class="col-md-6 col-lg-5 d-none d-md-block">
              {% load static %} <img src="{% static "tracker/media/car.jpg" %}"
              alt="login form" class="img-fluid" style="border-radius: 1rem 0 0
              1rem;" />
            </div>
            <div class="col-md-6 col-lg-7 d-flex align-items-center">
              <div class="card-body p-4 p-lg-5 text-black">
                <form method="POST">
                  <div class="d-flex align-items-center mb-3 pb-1">
                    <img src="{% static "tracker/media/logo.png" %}" alt="Logo" style="margin-right: 10px;"
                    width="80" height="80">
                    <span class="h1 fw-bold mb-0">Tracking App</span>
                  </div>

                  <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px">
                    Sign into your account
                  </h5>

                  <div class="form-outline mb-4">
                    <!-- <form method="POST"> -->
                    {% csrf_token %} {{ login_form|crispy }}
                    <!-- </form> -->
                  </div>

                  <div class="pt-1 mb-4">
                    <button
                      class="btn btn-dark btn-lg btn-block form-control"
                      type="submit"
                    >
                      Log In
                    </button>
                  </div>

                  <p class="mb-5 pb-lg-2" style="color: #393f81">
                    Don't have an account?
                    <a href="/register" style="color: #393f81">Register here</a>
                  </p>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

mysite/tracker/templates/tracker/register.html
{% extends "base.html" %} {% block content %} {% load crispy_forms_tags %}

<!--Register-->
<div class="container py-5">
  <h1>Register</h1>
  <form method="POST">
    {% csrf_token %} {{ register_form|crispy }}
    <button class="btn btn-primary" type="submit">Register</button>
  </form>
  <p class="text-center">
    If you already have an account, <a href="/login">login</a> instead.
  </p>
</div>

{% endblock %}

mysite/tracker/templates/tracker/tracker.html
{% extends 'base.html' %} {% block content%}

<h3>Trip data</h3>

<div class="row">
  <div class="col-md-8">
    <p>Trip id: {{ trip_number }}</p>
    <div id="map" style="width: 100%; height: 600px"></div>
    <br />
    <div class="d-flex justify-content-between">
      <div>
        <a href="?trip_number=1" type="button" class="btn btn-primary{% if trip_number == 1 %} disabled{% endif %}"
          ><<</a
        >
        <a href="{{ prev_trip_url }}" type="button" class="btn btn-primary{% if trip_number == 1 %} disabled{% endif %}"
          >PREVIOUS TRIP</a
        >
        <a
          href="{{ next_trip_url }}"
          type="button"
          class="btn btn-primary{% if trip_number == last_trip_number %} disabled{% endif %}"
          >NEXT TRIP</a
        >
        <a
          href="?trip_number={{ last_trip_number }}"
          type="button"
          class="btn btn-primary{% if trip_number == last_trip_number %} disabled{% endif %}"
          >>></a
        >
      </div>
      <div>
        <a href="{% url 'tracker:trip_list' %}" type="button" class="btn btn-success">VIEW ALL TRIPS LIST</a>
      </div>
    </div>

    <script>
      {% include 'tracker/includes/map_markers.html' %}

      var map = L.map('map');
      var latlngs = {{coordinates}};
      var polyline = L.polyline(latlngs, {color: 'blue', weight: 5}).addTo(map);
      var marker_start = L.marker({{coordinates|first}}, {icon: greenIcon}).addTo(map);
      marker_start.bindPopup("<b>Trip start location:</b><br>{{start_address}}").openPopup();
      var marker_finish = L.marker({{coordinates|last}}, {icon: redIcon}).addTo(map);
      marker_finish.bindPopup("<b>Trip end location:</b><br>{{end_address}}").openPopup();

      // zoom the map to the polyline
      map.fitBounds(polyline.getBounds());

      L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map);
    </script>
  </div>
  <div class="col-md-4">
    <h5>Trip details</h5>
    <table class="table">
      <tbody>
        <tr>
          <th>Start address</th>
          <td>{{ start_address }}</td>
        </tr>
        <tr>
          <th>Start coordinates</th>
          <td>{{ coordinates|last|join:", " }}</td>
        </tr>
        <tr>
          <th>End address</th>
          <td>{{ end_address }}</td>
        </tr>
        <tr>
          <th>End coordinates</th>
          <td>{{ coordinates|last|join:", " }}</td>
        </tr>
        <tr>
          <th>Start time</th>
          <td>{{ times.0 }}</td>
        </tr>
        <tr>
          <th>End time</th>
          <td>{{ times.1 }}</td>
        </tr>
        <tr>
          <th>Duration</th>
          <td>{{ times.2 }}</td>
        </tr>
        <tr>
          <th>Distance</th>
          <td>{{ distance }} km</td>
        </tr>
        <tr>
          <th>Top speed</th>
          <td>{{ top_speed }} km/h</td>
        </tr>
      </tbody>
    </table>
    <br />
    {% comment %} Add the delete button and form {% endcomment %}
    {% if user.is_authenticated %}
    <form method="post" action="{% url 'tracker:delete_nth_trip' %}">
      {% csrf_token %}
      <input type="hidden" name="trip_number" value="{{ trip_number }}" />
      <button type="submit" class="btn btn-danger">DELETE TRIP</button>
    </form>
    {% else %}
    <a href="/login" style="color: red">Log in to delete a trip</a>
    {% endif %}
  </div>
</div>

<!-- Add the Plotly CSS and JavaScript code -->
<style>
  /* Plotly CSS styles */
  #graph_placeholder {
    width: 100%;
    height: 500px; /* Adjust the height as needed */
  }
</style>

<script
  src="https://cdnjs.cloudflare.com/ajax/libs/plotly.js/2.24.2/plotly.min.js"
  integrity="sha512-dAXqGCq94D0kgLSPnfvd/pZpCMoJQpGj2S2XQmFQ9Ay1+96kbjss02ISEh+TBNXMggGg/1qoMcOHcxg+Op/Jmw=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
></script>
</br>
<div id="graph_placeholder">{{ speed_graph_html | safe }}</div>

<div id="graph_placeholder">{{ temp_graph_html | safe }}</div>

<div id="graph_placeholder">{{ coolant_temp_graph_html | safe }}</div>

<div id="graph_placeholder">{{ engine_rpm_graph_html | safe }}</div>

{% endblock %}

mysite/tracker/templates/tracker/trip_list.html
{% extends 'base.html' %} {% block content %}

<h3>All trips list</h3>

<div class="container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Trip ID</th>
        <th>Start datetime</th>
        <th>End datetime</th>
        <th>Distance</th>
        <th>Details</th>
      </tr>
    </thead>
    <tbody>
      {% for trip in trip_list %}
      <tr onclick="window.location='/?trip_number={{ trip.Trip_ID }}';" style="cursor: pointer">
        <td>{{ trip.Trip_ID }}</td>
        <td>{{ trip.Start_datetime }}</td>
        <td>{{ trip.End_datetime }}</td>
        <td>{{ trip.Distance }} km</td>
        <td><a href="/?trip_number={{ trip.Trip_ID }}">TRIP DETAILS</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <!-- Pagination -->
  <nav aria-label="Trip Pagination">
    <ul class="pagination justify-content-center">
      {% if trip_list.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ trip_list.previous_page_number }}">Previous</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
      </li>
      {% endif %} {% for page in trip_list.paginator.page_range %} {% if trip_list.number == page %}
      <li class="page-item active" aria-current="page">
        <a class="page-link" href="#">{{ page }} <span class="sr-only"></span></a>
      </li>
      {% else %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page }}">{{ page }}</a>
      </li>
      {% endif %} {% endfor %} {% if trip_list.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ trip_list.next_page_number }}">Next</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
      </li>
      {% endif %}
    </ul>
  </nav>
</div>

{% endblock %}